export const PRODUCTS_INIT = 'PRODUCTS_INIT'; 

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_START = 'ADD_PRODUCT_START';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

export const AUTH_OPEN = 'AUTH_OPEN';
export const AUTH_CLOSE = 'AUTH_CLOSE';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADDUSER_FAIL = 'ADDUSER_FAIL';
export const ADDUSER_SUCCESS = 'ADDUSER_SUCCESS';
export const ADDUSER_START = 'ADDUSER_START';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_START = 'EDIT_PRODUCT_START';
export const EDIT_PRODUCT_FAIL = 'EDIT_PRODUCT_FAIL';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';

export const FILTER_PRODUCTS_ARRAY = 'FILTER_PRODUCTS_ARRAY';
export const FILTER_OFF = 'FILTER_OFF';
export const FILTER_ON = 'FILTER_ON';

export const EDIT_OPEN = 'EDIT_OPEN';
export const EDIT_CLOSE = 'EDIT_CLOSE';
export const SHOW_OPEN = 'SHOW_OPEN';
export const SHOW_CLOSE = 'SHOW_CLOSE';
export const ADD_OPEN = 'ADD_OPEN';
export const ADD_CLOSE = 'ADD_CLOSE';
export const GET_ISADMIN = 'GET_ISADMIN';
export const ISADMIN_SUCCESS = 'ISADMIN_SUCCESS';
export const ISADMIN_FAIL = 'ISADMIN_FAIL';


export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
